export const ChatEventType = {
    CREATE_CONVERSATION: 'CREATE_CONVERSATION',
    JOIN_CONVERSATION: 'JOIN_CONVERSATION',
    UPDATE_CONVERSATION: 'UPDATE_CONVERSATION',
    LEAVE_CONVERSATION: 'LEAVE_CONVERSATION',
    SEND_MESSAGE: 'SEND_MESSAGE',
    CREATE_THREAD: 'CREATE_THREAD',
    JOIN_TEAM: 'JOIN_TEAM',
    LEAVE_TEAM: 'LEAVE_TEAM',
    ASSIGN_CHANNEL_ADMIN: 'ASSIGN_CHANNEL_ADMIN',
    ASSIGN_TEAM_ADMIN: 'ASSIGN_TEAM_ADMIN',
    USER_STATUS: 'USER_STATUS',
    ADD_USER: 'ADD_USER',
    REMOVE_USER: 'REMOVE_USER',
    SEND_NOTIFICATION: 'SEND_NOTIFICATION',
    DELETE_CONVERSATION: 'DELETE_CONVERSATION',
  };

  export const ResponseCode = {
    INVALID_TOKEN: 'token_not_valid',
    SESSION_INVALID_TOKEN: 'session_invalid_token',
    SESSION_INVALID_CODE: 'session_invalid_code',
    MATTERMOST_NOT_FOUND: 'mattermost_account_not_found',
    NOT_ENOUGH_SPACES: 'not_enough_spaces',
  };